version: 0.0
os: linux

files:
  - source: Week-4/NodejsProject/app1/
    destination: /var/www/app1

  - source: app2/
    destination: Week-4/NodejsProject/app2/
    
file_exists_behavior: OVERWRITE

permissions:
  - object: Week-4/NodejsProject/app1/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: Week-4/NodejsProject/app2/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: Week-4/NodejsProject/scripts/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: Week-4/NodejsProjectscripts/after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: Week-4/NodejsProject/scripts/start_server.sh
      timeout: 60
      runas: root
