version: 0.0
os: linux

files:
  - source: Week-4/NodejsProject/app1/
    destination: /var/www/app1

  - source: Week-4/NodejsProject/app2/
    destination: /var/www/app2
    
file_exists_behavior: OVERWRITE

permissions:
  - object: Week-4/NodejsProject/app1
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: Week-4/NodejsProject/app2
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: Week-4/NodejsProject/scripts/restart_pm2.sh
      timeout: 300
      runas: root