version: 0.0
os: linux

files:
  - source: Week-5/todoapp/
    destination: /var/www/app
    
file_exists_behavior: OVERWRITE

permissions:
  - object: Week-5/todoapp/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: Week-5/scripts/docker.sh
      timeout: 300
      runas: root


# version: 0.0
# resources:
#   - TargetService:
#       Type: AWS::ECS::Service
#       Properties:
#         TaskDefinition: "arn:aws:ecs:region:account-id:task-definition/task-def-name:1"
#         LoadBalancerInfo:
#           ContainerName: "nodejs-app"
#           ContainerPort: 3000
# hooks:
#   BeforeInstall:
#     - location: scripts/deploy.sh
#       timeout: 300
#       runas: root
