version: 0.2

env:
  variables:
    AWS_REGION: "us-east-2"
    ECR_REPO_NAME: "ECRNodeJSRepo"

  
phases:

  pre_build:
    commands:
      - echo "Logging into AWS ECR..."
      - echo "${AWS_REGION} ${ECR_REPOSITORY_URL}"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
      - echo "Removing old Docker images (if any)..."
      - docker images -q $ECR_REPO_NAME && docker rmi -f $(docker images -q $ECR_REPO_NAME) || echo "No old images found."

  build:
    commands:
      - echo "Building Docker image for Node.js To-Do App..."
      - pwd
      - ls -la
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $ECR_REPOSITORY_URL:latest

  post_build:
    commands:
      - echo "Pushing Docker image to AWS ECR..."
      - docker push $ECR_REPOSITORY_URL:latest
      - echo "Build and push completed successfully!"

artifacts:
  files:
    - "**/*"
    - scripts
