pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '3')) 
    }

    environment {
        TF_DIR = "/terraform-week3/environments/dev"  
    }

stages{
    stage('Debug Workspace') {
        steps {
            script {
                sh 'pwd'    // Print the current working directory
                sh 'ls -R'  // List all files to confirm terraform-week3 exists
            }
        }
    }
}
}