pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    environment {
        VAULT_ADDR = "http://18.118.27.69:8200"
        VAULT_TOKEN = credentials('vault-token')
        ENV_DIR = "Week-3/terraform-week3/environments/dev"
    }

    stages {
        stage('SCM Checkout') {
            steps {
                checkout scm
                sh "ls -R"  // Debugging: Show the structure after checkout
            }
        }

        stage('Verify Environment Directory') {
            steps {
                script {
                    def dirExists = checkEnvDir()
                    if (!dirExists) {
                        error "ERROR: Terraform environment directory ${ENV_DIR} does not exist!"
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                sh "cd ${ENV_DIR} && terraform init"
            }
        }

        stage('Terraform Apply') {
            steps {
                sh "cd ${ENV_DIR} && terraform apply -auto-approve"
            }
        }

        // stage('Terraform Destroy') {
        //     steps {
        //         sh "cd ${ENV_DIR} && terraform destroy -auto-approve"
        //     }
        // }
    }

    post {
        always {
            script {
                echo "Terraform pipeline completed with status: ${currentBuild.currentResult} in ${env.ENV_DIR}"
            }
        }
    }
}