version: 0.0
os: linux

files:
  - source: app1/
    destination: /var/www/app1
    file_exists_behavior: OVERWRITE

  - source: app2/
    destination: /var/www/app2
    file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/app1
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /var/www/app2
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
