---
- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/django.conf
  become: yes

- name: Ensure the default Nginx configuration is removed
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  become: yes

- name: Restart Nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
